services:
  app:
    build:
      context: ./swifty-companion
      dockerfile: Dockerfile
    container_name: swifty-companion
    volumes:
      - ./swifty-companion:/swifty-companion
      - app_node_modules:/swifty-companion/node_modules
      - ${ANDROID_SDK_PATH}:/host-android-sdk
    network_mode: host
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - ANDROID_HOME=/host-android-sdk
      - ADB_SERVER_SOCKET=tcp:0.0.0.0:5037

  api:
    build:
      context: ./swifty-api
      dockerfile: Dockerfile
    container_name: swifty-api
    volumes:
      - ./swifty-api:/swifty-api
      - api_node_modules:/swifty-api/node_modules
    network_mode: host
    stdin_open: true
    tty: true
    env_file: .env

volumes:
  app_node_modules:
  api_node_modules:
